# MkDocs configuration
# Based on https://github.com/paperless-ngx/paperless-ngx/blob/main/mkdocs.yml
site_name: Paperless Scripts Collection

theme:
  name: material
  logo: assets/logo_white.svg
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.expand
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github
repo_url: https://github.com/marcelbrueckner/paperless.sh
repo_name: marcelbrueckner/paperless.sh
edit_uri: blob/main/docs/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - toc:
      toc_depth: 2
  - pymdownx.highlight:
      pygments_style: zenburn
      noclasses: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
        alternate_style: true
  - footnotes
strict: true
nav:
  - index.md
  - Pre-consumption: pre-consumption/
  - Post-consumption: post-consumption/
  - API: api/
  - Other: other/
  - About:
    - Contributing: about/contributing.md

exclude_docs: |
  *.local.md

copyright: Copyright &copy; 2024 <a href="https://marcelbrueckner.de">Marcel Brückner</a> and contributors
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/marcelbrueckner/paperless.sh

plugins:
  - search
  - literate-nav:
      nav_file: README.md
